### ISSUE TITLE
display issue

### ISSUE THREAD

**Issue by nbehrnd** [OpenChemistry/codmolecules#1]
Accessing this format of DataWarrior's selection of the COD for the first time, I was concerned by the way how GitHub represents the data.  Because the display of the sub-folders may be interpreted as if a good number could be missing:

![truncate](https://user-images.githubusercontent.com/19709084/106364459-10b36a00-6327-11eb-8a72-8069c37b1d86.png)

Intrigued by this, I compared the data set used in this commit as source as provided by DataWarrior (snapshot June, 2020) with the data set available here.  Contrary to speculation, using the COD ID number as sole criterion of comparison, there are only 40 entries currently absent (this corresponds to less than 0.16 permille).

I do not know if this discrepancy between of the data present in the project, and the ones displayed in GitHub's UI is because of a setup by GitHub's parameters and may be influenced by the project's owner.  Yet I think it is worth to inform the user of this compilation, e.g., in the documentation, that cloning of the project basically offers access to all of the data claimed (and not only about half of it).

The attached .zip includes the documentation / screening (a Jupyter notebook) as well as a listing of the 40 entries currently missing.

[transfertest.zip](https://github.com/OpenChemistry/codmolecules/files/5898481/transfertest.zip)

**Comment by ghutchis** [comment]
I'm open to other organizational methods. For this case, I exported from the DataWarrior version, then split using Open Babel.

The main reason for subdirectories is that most filesystems (Linux, Mac, Windows) get cranky with too many files in a directory.

One thought I had was to organize into 100 subdirectories by the last 2 digits of the COD code? Right now, it's ~2500 compounds per directory.

If you have a suggestion about the README, (e.g., how to word / clarify) -- that would be great.

**Comment by vaitkus** [comment]
> The main reason for subdirectories is that most filesystems (Linux, Mac, Windows) get cranky with too many files in a directory.

I would like to note that the COD CIF tree is organised in a very similar fashion [1] for just this reason. Well, maybe even a bit more extreme, since each final directory in the layout contains at most a 100 files. For example, file 1234567.cif is placed under 1/23/56/, file 7456893.cif is placed under 7/45/68/, etc.

Since SDF and CIF files have a 1:1 mapping, maybe it would be worthwhile to adopt a similar layout here as well?

[1] https://www.crystallography.net/cod/cif/

**Comment by ghutchis** [comment]
@vaitkus - sounds like a great idea. Since I'd like to move to SD files generated from `cod-tools` that will greatly improve the workflow.

**Comment by nbehrnd** [comment]
Interested in the topic, I doodled a little about resorting this data set with Python in the notebook attached below.  While it is possible to delegate this task, this sequential approach is slower, than anticipated.  Especially if one wants to keep the data «as such» monitored by `git` and thus calls for `git mv foo_old_position foo_new_position`.  This is the main reason why I stopped a test run processing about 2k of data.  The intended creation of folders containing up to 100 individual data sets was observed.

So I _speculate_, a faster approach then the one of the notebook below is to 1) start from scratch, 2) perform the conversion to yield `.sdf.gz`, and 3) to sort them with a set of regular expressions in sub-folders matching the pattern by the COD as indicated by Antanas Vaitkus.

[reorganizer.ipynb.zip](https://github.com/OpenChemistry/codmolecules/files/5914085/reorganizer.ipynb.zip)

**Comment by ghutchis** [comment]
I'm running this reorganization already using `git mv`. It'll probably take a bit, but hold tight...

**Comment by ghutchis** [comment]
Speaking of which, after about 10 hours, it seems to be finished with 65771f06f0900b4b4a1ffc3e17e7ed0f1043eb15

**Comment by ghutchis** [comment]
For reference, the shell script (using ZSH in my case) was:
```
find . -name "*.gz" >files;
for x in `cat files`; do
  f=${x:5}; d1=${f[1]}; d2=${f[2,3]}; d3=${f[4,5]}; 
  mkdir -p ${d1}/${d2}/${d3}
  git mv $x ${d1}/${d2}/${d3}/$f
done
```

**Comment by nbehrnd** [comment]
Hoovering in GiHub's GUI with the mouse over "codmolecules/6/00"
indicates "This path skips through empty directories" even if, e.g.,
path "/6/00/04/" contains six files is a bit odd.  Similar in the tree
"codmolecules/1/" which displays sub-folder "20/00" with then five
files.  I don't know why and how this happened, but because the files
are organized with the pattern of the COD, I consider the initial
issue resolved; the ticket may be closed.

Last but not least, equally I thank you for the showcase of RE's
deployment in a shell script.
